services:
  backend:
    build:
      context: ./backend
    ports:
      - "9009:9009"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
    volumes:
      - ./backend/chats:/app/chats
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend
